general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    color = rgba(20, 20, 28, 1.0)
    blur_passes = 3
    blur_size = 7
}

# TIME
label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 1.0)
    font_size = 96
    font_family = JetBrains Mono Bold
    position = 0, 180
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(154, 162, 197, 1.0)
    font_size = 24
    font_family = JetBrains Mono
    position = 0, 90
    halign = center
    valign = center
}

# BACKING SHAPE
shape {
    monitor =
    size = 460, 130
    color = rgba(20, 20, 28, 0.8)
    rounding = 15
    border_size = 4
    border_color = rgba(128, 168, 235, 1.0)
    position = 0, -120
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 400, 70
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(128, 168, 235, 1.0)
    inner_color = rgba(30, 30, 40, 0.8)
    font_color = rgba(255, 255, 255, 1.0)
    fade_on_empty = false
    placeholder_text = <span foreground="##9AA2C5">Password</span>
    hide_input = false
    check_color = rgba(128, 168, 235, 1.0)
    fail_color = rgba(128, 168, 235, 1.0)
    fail_text = <i>$FAIL</i>
    font_family = JetBrains Mono
    position = 0, -120
    halign = center
    valign = center
}
